/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorMascota;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Mascota;

/**
 *
 * @author Rodrigo
 */
public class VentanaBuscarMascota extends javax.swing.JFrame {

    /**
     * Creates new form VentanaBuscarMascota
     */
    public VentanaBuscarMascota() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_seleccionBusqueda = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lbl_buscarMascota = new javax.swing.JLabel();
        rb_buscarNombre = new javax.swing.JRadioButton();
        rb_buscarTipo = new javax.swing.JRadioButton();
        lbl_nombre = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();
        cmb_tipo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_mascotas = new javax.swing.JTable();
        btn_modificar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();

        setSize(new java.awt.Dimension(800, 600));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_buscarMascota.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 48)); // NOI18N
        lbl_buscarMascota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconpet.png"))); // NOI18N
        lbl_buscarMascota.setText("Buscar Mascota");
        lbl_buscarMascota.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lbl_buscarMascotaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        bg_seleccionBusqueda.add(rb_buscarNombre);
        rb_buscarNombre.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rb_buscarNombre.setText("Buscar Por Nombre");
        rb_buscarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_buscarNombreActionPerformed(evt);
            }
        });

        bg_seleccionBusqueda.add(rb_buscarTipo);
        rb_buscarTipo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rb_buscarTipo.setText("Buscar Por Tipo");
        rb_buscarTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_buscarTipoActionPerformed(evt);
            }
        });

        lbl_nombre.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_nombre.setText("Nombre:");

        txt_nombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btn_buscar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_buscar.setText("BUSCAR");
        btn_buscar.setEnabled(false);
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        cmb_tipo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmb_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "(Seleccione Tipo)", "Perro", "Gato", "Tortuga" }));
        cmb_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_tipoActionPerformed(evt);
            }
        });

        tbl_mascotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "N. MASCOTA", "EDAD", "TIPO", "HIST. MEDICO", "NRO. ATENCIONES", "POSEE DUEÑO", "NOMBRE DUEÑO", "DESCRIPCIÓN"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Boolean.class, java.lang.Integer.class, java.lang.Boolean.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_mascotas);

        btn_modificar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/modify.png"))); // NOI18N
        btn_modificar.setText("MODIFICAR");
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });

        btn_eliminar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ERASE.png"))); // NOI18N
        btn_eliminar.setText("ELIMINAR");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(188, 188, 188)
                                .addComponent(rb_buscarNombre)
                                .addGap(18, 18, 18)
                                .addComponent(rb_buscarTipo))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(200, 200, 200)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbl_nombre)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cmb_tipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(162, 162, 162)
                                .addComponent(lbl_buscarMascota)))
                        .addGap(0, 169, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_eliminar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_modificar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_buscarMascota)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_buscarNombre)
                    .addComponent(rb_buscarTipo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_nombre)
                            .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_buscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_modificar)
                    .addComponent(btn_eliminar))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_tipoActionPerformed

        
        
        
    }//GEN-LAST:event_cmb_tipoActionPerformed

    private void rb_buscarTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_buscarTipoActionPerformed
        
        if (rb_buscarTipo.isSelected()){
            btn_buscar.setEnabled(true);
            cmb_tipo.setVisible(true);
            txt_nombre.setEnabled(false);
        }
        
    }//GEN-LAST:event_rb_buscarTipoActionPerformed

    private void lbl_buscarMascotaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lbl_buscarMascotaAncestorAdded
        cmb_tipo.setVisible(false);
        txt_nombre.setEnabled(false);
        
    }//GEN-LAST:event_lbl_buscarMascotaAncestorAdded

    private void rb_buscarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_buscarNombreActionPerformed
        
        if (rb_buscarNombre.isSelected()){
            btn_buscar.setEnabled(true);
            cmb_tipo.setVisible(false);
            txt_nombre.setEnabled(true);
        }
    }//GEN-LAST:event_rb_buscarNombreActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        
        ArrayList<Mascota>listaMascotas = new ArrayList<>();
        ControladorMascota ctrlMascota = new ControladorMascota();
        
        if (txt_nombre.isEnabled()){
            try {
                
                String nombre = txt_nombre.getText();
                listaMascotas = ctrlMascota.mascotaListar(nombre);
        
                DefaultTableModel tablaModelo = (DefaultTableModel)tbl_mascotas.getModel();
        
                tablaModelo.setRowCount(0);
        
                for (Mascota mascota: listaMascotas) {
            
                    Object[] registro = {
                
                        mascota.getId_mascota(),
                        mascota.getNom_mascota(),
                        mascota.getEdad_mascota(),
                        mascota.getTipo_mascota(),
                        mascota.isAte_hist_mascota(),
                        mascota.getCant_ate_mascota(),
                        mascota.isProp_mascota(),
                        mascota.getNom_prop(),
                        mascota.getDesc_mascota()  
                    };
                
                    tablaModelo.addRow(registro);   
                }
        
            }
        
            catch (Exception err) {
            
                System.out.println("ERROR: " + err.getMessage());
            
            }
        }
        
        
        
        else if (cmb_tipo.isEnabled()){
            
            try {
                
                String tipo = cmb_tipo.getSelectedItem().toString();
                listaMascotas = ctrlMascota.mascotaListarCombo(tipo);
        
                DefaultTableModel tablaModelo = (DefaultTableModel)tbl_mascotas.getModel();
        
                tablaModelo.setRowCount(0);
        
                for (Mascota mascota: listaMascotas) {
            
                    Object[] registro = {
                
                        mascota.getId_mascota(),
                        mascota.getNom_mascota(),
                        mascota.getEdad_mascota(),
                        mascota.getTipo_mascota(),
                        mascota.isAte_hist_mascota(),
                        mascota.getCant_ate_mascota(),
                        mascota.isProp_mascota(),
                        mascota.getNom_prop(),
                        mascota.getDesc_mascota()  
                    };
                
                    tablaModelo.addRow(registro);   
                }
        
            }
        
            catch (Exception err) {
            
                System.out.println("ERROR: " + err.getMessage());
            
            }            
        }
    
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed

        try {
            
            int indice = tbl_mascotas.getSelectedRow();
            int id = (int)tbl_mascotas.getValueAt(indice, 0);
            VentanaModificarMascota vmm = new VentanaModificarMascota(id);
            vmm.setVisible(true);
            vmm.setResizable(false);
            vmm.setLocationRelativeTo(null);
            vmm.setTitle("MediPet - Modificar Mascota");
            Toolkit miPantalla = Toolkit.getDefaultToolkit();
            Image iconoPet = miPantalla.getImage("src/img/iconpet.png");
            vmm.setIconImage(iconoPet);
        }
        
        catch (Exception err) {
            JOptionPane.showMessageDialog(rootPane, "NO SE HA SELECCIONADO NINGÚN REGISTRO PARA MODIFICAR");
        }
        
        
        
        
        
        

        
        
        
        
    }//GEN-LAST:event_btn_modificarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        ControladorMascota ctrlMascota = new ControladorMascota();  
        try {
            
            int indice = tbl_mascotas.getSelectedRow();
            String id = tbl_mascotas.getValueAt(indice, 0).toString();
        
            ctrlMascota.mascotaEliminar(id);
            btn_buscarActionPerformed(evt);
            JOptionPane.showMessageDialog(rootPane, "MASCOTA ELIMINADA CORRECTAMENTE");
        }
        
        catch (Exception err) { 
            
            JOptionPane.showMessageDialog(rootPane, "ERROR: NO HA SELECCIONADO NINGUN REGISTRO PARA ELIMINAR");
            
        }
        
        
        
        
    }//GEN-LAST:event_btn_eliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaBuscarMascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaBuscarMascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaBuscarMascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaBuscarMascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaBuscarMascota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg_seleccionBusqueda;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JComboBox<String> cmb_tipo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_buscarMascota;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JRadioButton rb_buscarNombre;
    private javax.swing.JRadioButton rb_buscarTipo;
    private javax.swing.JTable tbl_mascotas;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
